package main

// Generated by https://quicktype.io

/*
Contiene I dati di:
	=> TS - Orario in cui è stata fatta la misurazione
	=> Pm25 -  Indice inquinamento polveri sottili
			=> Indice sulla qualità dell'aria generalizzata
			=> Indice di concentrazione delle polveri sottili nell'aria
	=> Condition - Condizione meteorologica al momento della misurazione
	=> Humidity - Livello di Umidità al momento della misura
*/
type Data struct {
	Ts          string      `json:"ts"`
	Pm25        Pm25        `json:"pm25"`
	Condition   string      `json:"condition"`
	Humidity    int64       `json:"humidity"`
	Pressure    int64       `json:"pressure"`
	Wind        Wind        `json:"wind"`
	Temperature int64       `json:"temperature"`
	Coordinates Coordinates `json:"coordinates"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Pm25 struct {
	Aqi           int64   `json:"aqi"`
	Concentration float64 `json:"concentration"`
}

type Wind struct {
	Speed     float64 `json:"speed"`
	Direction int64   `json:"direction"`
}
